name: fish_freshness_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Image & Camera
  image_picker: ^1.0.7
  image: ^4.0.17
  camera: ^0.11.0

  # ML / TFLite
  tflite_flutter: ^0.11.0

  # HTTP & Storage 
  http: ^1.1.0
  shared_preferences: ^2.2.3

  # Utilities
  path_provider: ^2.1.2
  desktop_drop: ^0.4.3
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fish_model.tflite
    - assets/images/fish_eye_guide.jpeg
    - assets/images/fish_gill_guide.jpeg
    - assets/images/fish_meat_guide.jpeg
    - assets/images/profile_photo.jpg