// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQogA18kLBZhhffXEHP6wFdvJ1eU5cbOg',
    appId: '1:89947364484:web:f427e0f13d9637d981b6d1',
    messagingSenderId: '89947364484',
    projectId: 'freshnet-e0c44',
    authDomain: 'freshnet-e0c44.firebaseapp.com',
    storageBucket: 'freshnet-e0c44.firebasestorage.app',
    measurementId: 'G-XRWBY6FNK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMKIHuPMiPlq5VPQTmdwQjfh8lyLoEtDw',
    appId: '1:89947364484:android:ba021c8bf9c8ec6b81b6d1',
    messagingSenderId: '89947364484',
    projectId: 'freshnet-e0c44',
    storageBucket: 'freshnet-e0c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfZIfNwWLdjVQ3vTsxzyclTH4MwaS4b4',
    appId: '1:89947364484:ios:37e162f770cd7df681b6d1',
    messagingSenderId: '89947364484',
    projectId: 'freshnet-e0c44',
    storageBucket: 'freshnet-e0c44.firebasestorage.app',
    iosBundleId: 'com.example.fishFreshnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfZIfNwWLdjVQ3vTsxzyclTH4MwaS4b4',
    appId: '1:89947364484:ios:37e162f770cd7df681b6d1',
    messagingSenderId: '89947364484',
    projectId: 'freshnet-e0c44',
    storageBucket: 'freshnet-e0c44.firebasestorage.app',
    iosBundleId: 'com.example.fishFreshnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQogA18kLBZhhffXEHP6wFdvJ1eU5cbOg',
    appId: '1:89947364484:web:477461f2234fc87e81b6d1',
    messagingSenderId: '89947364484',
    projectId: 'freshnet-e0c44',
    authDomain: 'freshnet-e0c44.firebaseapp.com',
    storageBucket: 'freshnet-e0c44.firebasestorage.app',
    measurementId: 'G-QP3ZD2CX7W',
  );
}
